# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmgr', '0003_auto_20160721_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
    ]
