# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmgr', '0004_remove_membership_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='No Title Provided', max_length=50),
        ),
    ]
